### ISSUE TITLE
Upstream repo updates

### ISSUE THREAD

**Issue by anarion80** [MichalKrasowski/tech-controllers#23]
Hi @MichalKrasowski. I was added as collaborator to the upstream repo and I would like to release a new version of the integration. I have done many changes, some based on your fork as well, so I would appreciate if you could comment and more importantly test the version from here: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/pull/55

Thanks!

**Comment by MichalKrasowski** [comment]
Great work, let me test it today-tomorrow and come back

**Comment by MichalKrasowski** [comment]
All good!

**Comment by anarion80** [comment]
Thanks!
