### ISSUE TITLE
Turn off zone Error

### ISSUE THREAD

**Issue by jontofront** [MichalKrasowski/tech-controllers#4]
Home Assistant 2021.11.5
Tech module L-4-WiFi (v.1.1.10)

![image](https://user-images.githubusercontent.com/37038426/145728411-068efbd1-8980-4d77-a47a-1c33604ba47f.png)

@MichalKrasowski can you check did you get error when trying to turn off zone?

**Comment by MichalKrasowski** [comment]
No, didn't experience this error. My unit is L-4 Wifi

**Comment by jontofront** [comment]
Maybe you have ideas on where to start the search problem?

**Comment by mariusnauj** [comment]
Hello,

For me the same error. 
jontofront which thermostat cards you are using?

**Comment by jontofront** [comment]
@mariusnauj  simple-thermostat
https://github.com/nervetattoo/simple-thermostat

**Comment by facenty** [comment]
I have met the same issue, I will try to fix it and I'll post the result.

**Comment by mariusnauj** [comment]
Ok, and another thing I have room thermostat with humidity it's possible to forward humidity data to Homeassistant?

**Comment by souzen** [comment]
I have experienced same error message when I tried to update multiple climate entities in single scene. Today I double checked and it works perfectly fine. 
@jontofront do You have logs output?
