### ISSUE TITLE
Integration is not visible

### ISSUE THREAD

**Issue by Cosik** [MichalKrasowski/tech-controllers#7]
Hello, I installed it via HACS,

`[core-ssh ~]$ ls config/custom_components/tech/
CONTRIBUTING.md  __init__.py      config_flow.py   images           strings.json     test_tech.py
LICENSE.md       climate.py       const.py         manifest.json    tech.py          translations
`
So currently this addon is not usable with HA.

## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | failed to load: timeout
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.23.0
Stage | running
Available Repositories | 1072
Downloaded Repositories | 4

</details>

<details><summary>Airly</summary>

can_reach_server | ok
-- | --
requests_remaining | 40
requests_per_day | 100

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 28.8 GB
disk_used | 6.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.3.0), Mosquitto broker (6.0.1), HoyMiles Solar Data Gateway Add-on (0.24), Wmbusmeters (W-MBus to MQTT) (0.2.20), Studio Code Server (4.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 1
views | 4
mode | storage

</details>

**Comment by Cosik** [comment]
It appear after second (?) restart(?)

**Comment by MichalKrasowski** [comment]
@Cosik , can we close then?

**Comment by Cosik** [comment]
yes.
