### ISSUE TITLE
Cannot connect to integration - L4-WiFi (v.1.1.10)

### ISSUE THREAD

**Issue by Drakenzo** [MichalKrasowski/tech-controllers#9]
Hello, 

while trying to add integration I'm facing below error:
![image](https://user-images.githubusercontent.com/64210551/194054207-e9a24515-cac4-4b0a-a86f-603170f55d5d.png)

Credential are good - when I'm giving wrong pass it says "Incorrect Password"
Please find below part of a logfile:

Traceback (most recent call last):
  File "/config/custom_components/tech/config_flow.py", line 53, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/tech/config_flow.py", line 26, in validate_input
    if not await api.authenticate(data["username"], data["password"]):
  File "/config/custom_components/tech/tech.py", line 65, in authenticate
    result = await self.post(path, post_data)
  File "/config/custom_components/tech/tech.py", line 56, in post
    raise TechError(response.status, await response.text())
custom_components.tech.tech.TechError: (400, '{"error":"Bad Request"}')

Have anyone faced the same issue and have a solution?

**Comment by Drakenzo** [comment]
@mariomikvere As far as i know only certain versions of the controller are supported

**Comment by mariomikvere** [comment]
> @mariomikvere As far as i know only certain versions of the controller are supported

I hope these are the versions that have been tried :)

**Comment by Drakenzo** [comment]
@mariomikvere These are supported:
L-4 Wifi, L-7, L-8, WiFi 8S, ST-8S WiFi

**Comment by Drakenzo** [comment]
@mariomikvere 
Solution to my problem:
https://github.com/MichalKrasowski/tech-controllers/pull/13/commits/4c2c3ec57b339efe12d83bf5d6179c6c8545f60f
